# tasks/execute_command_script.yml
---
- name: Run command or script with sudo
  command: "{{ item }}"
  when: not item.startswith('#')
  register: command_result
  ignore_errors: true
  become: true

- name: Save command/script result to control node
  copy:
    content: |
      {
        "host": {{ inventory_hostname | to_json }},
        "command_or_script": {{ item | to_json }},
        "exit_code": {{ command_result.rc }},
        "stdout": {{ command_result.stdout | to_json }},
        "stderr": {{ command_result.stderr | to_json }}
      }
    dest: "/tmp/audit_results/{{ inventory_hostname }}_{{ item | regex_replace('[^a-zA-Z0-9]', '_') }}.json"
  delegate_to: localhost
