# FILE: bandit.yaml
exclude_dirs: [ 'chromadb/test', 'bin', 'build', 'build', '.git', '.venv', 'venv', 'env','.github','examples','clients/js','.vscode', '*/tests/*', '.env*', '*.ipynb', '/src/sales_crm_backend/settings/*', '*enums*', 'src/automation_workflows/constants/enum.py', '*graphqlTypes.ts', '*graphqlTypes.tsx', '*/fixtures/*' ]
tests: [ ]
skips: [ ]
