quiet: false

check-for-app-update: true

parallelism: 3

# scope: "all-layers"

# default-catalogers: [ "go-module-file-cataloger", "go-module-binary-cataloger"]

format:
  json:
    pretty: true
  cyclonedx-json:
    pretty: true

golang:
  search-local-mod-cache-licenses: false
  search-remote-licenses: true

python:
  # when running across entries in requirements.txt that do not specify a specific version 
  # (e.g. "sqlalchemy >= 1.0.0, <= 2.0.0, != 3.0.0, <= 3.0.0"), attempt to guess what the version could
  # be based on the version requirements specified (e.g. "1.0.0"). When enabled the lowest expressible version 
  # when given an arbitrary constraint will be used (even if that version may not be available/published).
  guess-unpinned-requirements: false
  search-remote-licenses: true

javascript:
  search-remote-licenses: true
  npm-base-url: "https://registry.npmjs.org"