---
- - :permit
  - MIT
  - :who: 
    :why: 
    :versions: []
    :when: 2024-10-27 05:49:04.761648405 Z
- - :permit
  - BSD
  - :who: 
    :why: 
    :versions: []
    :when: 2024-10-27 05:49:37.294496455 Z
- - :permit
  - Apache 2.0
  - :who: 
    :why: 
    :versions: []
    :when: 2024-10-27 05:49:59.741080053 Z
- - :permit
  - New BSD
  - :who: 
    :why: 
    :versions: []
    :when: 2024-10-27 05:50:51.087187342 Z
- - :permit
  - Simplified BSD
  - :who: 
    :why: 
    :versions: []
    :when: 2024-10-27 05:50:57.885963159 Z
- - :permit
  - Python Software Foundation License
  - :who: 
    :why: 
    :versions: []
    :when: 2024-10-27 05:50:57.885963159 Z
- - :permit
  - Mozilla Public License 2.0
  - :who: 
    :why: 
    :versions: []
    :when: 2024-10-27 05:50:57.885963159 Z
